services:
  web:
    image: web
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: forum
    volumes:
      - ./sql:/docker-entrypoint-initdb.d